# Generated by Django 5.0.1 on 2024-01-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_list', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
